
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-16
owner: ucsb-cs156-f25
repo_name: team01-f25-16
pull_requests: [{"author":{"id":"U_kgDOBnO7gw","is_bot":false,"login":"quinnkos","name":"Quinn Koster"},"headRefName":"quinn.feature/create-UCSBOrganizationController","number":59,"title":"add controller for UCSBOrganization","url":"https://github.com/ucsb-cs156-f25/team01-f25-16/pull/59"},{"author":{"id":"U_kgDOBmEn_g","is_bot":false,"login":"mihir-s-05","name":""},"headRefName":"mihir-Articles-add-PUT","number":48,"title":"Added PUT(edit) functionality for existing Articles","url":"https://github.com/ucsb-cs156-f25/team01-f25-16/pull/48"},{"author":{"id":"U_kgDOBmEn_g","is_bot":false,"login":"mihir-s-05","name":""},"headRefName":"mihir-Articles-add-DELETE","number":47,"title":"Added DELETE endpoint for Articles by ID","url":"https://github.com/ucsb-cs156-f25/team01-f25-16/pull/47"},{"author":{"id":"U_kgDOBmEn_g","is_bot":false,"login":"mihir-s-05","name":""},"headRefName":"mihir-Articles-add-GET-single","number":46,"title":"Added GET endpoint for Articles for singular article by ID","url":"https://github.com/ucsb-cs156-f25/team01-f25-16/pull/46"}]
