
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-16
owner: ucsb-cs156-f25
repo_name: team01-f25-16
pull_requests: [{"author":{"id":"U_kgDOBnO7gw","is_bot":false,"login":"quinnkos","name":"Quinn Koster"},"headRefName":"quinn.feature/add-UCSBOrganization-get-endpoint","number":68,"title":"Quinn.feature/add ucsb organization get endpoint","url":"https://github.com/ucsb-cs156-f25/team01-f25-16/pull/68"},{"author":{"id":"MDQ6VXNlcjQyNTIxODgw","is_bot":false,"login":"omar882","name":"Omar Aboutaleb"},"headRefName":"HelpRequest-delete-single","number":67,"title":"Add delete endpoint for HelpRequest and added tests","url":"https://github.com/ucsb-cs156-f25/team01-f25-16/pull/67"},{"author":{"id":"U_kgDOCBQ7GQ","is_bot":false,"login":"Saqif-Ayaan","name":""},"headRefName":"revert-64-controller-recommendation-requests-run2","number":66,"title":"Revert \"Added controller for recommendation requests\"","url":"https://github.com/ucsb-cs156-f25/team01-f25-16/pull/66"},{"author":{"id":"U_kgDOBnO7gw","is_bot":false,"login":"quinnkos","name":"Quinn Koster"},"headRefName":"quinn.feature/create-UCSBOrganizationController","number":59,"title":"add controller for UCSBOrganization","url":"https://github.com/ucsb-cs156-f25/team01-f25-16/pull/59"}]
