
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-16
owner: ucsb-cs156-f25
repo_name: team01-f25-16
pull_requests: [{"author":{"id":"U_kgDOCBQ7GQ","is_bot":false,"login":"Saqif-Ayaan","name":""},"headRefName":"create-db-RecommendationRequests","number":56,"title":"Added db for RecommendationRequests","url":"https://github.com/ucsb-cs156-f25/team01-f25-16/pull/56"},{"author":{"id":"MDQ6VXNlcjQyNTIxODgw","is_bot":false,"login":"omar882","name":"Omar Aboutaleb"},"headRefName":"omar-HelpRequest-create-controller","number":55,"title":"Added controller for HelpRequest","url":"https://github.com/ucsb-cs156-f25/team01-f25-16/pull/55"},{"author":{"id":"U_kgDOC31Aag","is_bot":false,"login":"alexjh2","name":""},"headRefName":"aj-menuitems-get-by-id","number":52,"title":"aj-add GET by id for menuitems","url":"https://github.com/ucsb-cs156-f25/team01-f25-16/pull/52"},{"author":{"id":"U_kgDOBnO7gw","is_bot":false,"login":"quinnkos","name":"Quinn Koster"},"headRefName":"quinn-UCSBOrganization-create-db","number":51,"title":"added entity and repository classes and database migration file for d…","url":"https://github.com/ucsb-cs156-f25/team01-f25-16/pull/51"},{"author":{"id":"U_kgDOBmEn_g","is_bot":false,"login":"mihir-s-05","name":""},"headRefName":"mihir-Articles-add-PUT","number":48,"title":"Added PUT(edit) functionality for existing Articles","url":"https://github.com/ucsb-cs156-f25/team01-f25-16/pull/48"},{"author":{"id":"U_kgDOBmEn_g","is_bot":false,"login":"mihir-s-05","name":""},"headRefName":"mihir-Articles-add-DELETE","number":47,"title":"Added DELETE endpoint for Articles by ID","url":"https://github.com/ucsb-cs156-f25/team01-f25-16/pull/47"},{"author":{"id":"U_kgDOBmEn_g","is_bot":false,"login":"mihir-s-05","name":""},"headRefName":"mihir-Articles-add-GET-single","number":46,"title":"Added GET endpoint for Articles for singular article by ID","url":"https://github.com/ucsb-cs156-f25/team01-f25-16/pull/46"}]
