
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-16
owner: ucsb-cs156-f25
repo_name: team01-f25-16
pull_requests: [{"author":{"id":"U_kgDOCBQ7GQ","is_bot":false,"login":"Saqif-Ayaan","name":""},"headRefName":"create-del-recommendationrequests","number":77,"title":"Create DEL Endpoint for recommendation requests","url":"https://github.com/ucsb-cs156-f25/team01-f25-16/pull/77"},{"author":{"id":"U_kgDOCBQ7GQ","is_bot":false,"login":"Saqif-Ayaan","name":""},"headRefName":"create-put-recommendation-requests","number":76,"title":"Create PUT endpoint for recommendation requests","url":"https://github.com/ucsb-cs156-f25/team01-f25-16/pull/76"},{"author":{"id":"U_kgDOCBQ7GQ","is_bot":false,"login":"Saqif-Ayaan","name":""},"headRefName":"create-get-recommendation-requests","number":75,"title":"added get functionality to recommendation requests","url":"https://github.com/ucsb-cs156-f25/team01-f25-16/pull/75"}]
