
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-16
owner: ucsb-cs156-f25
repo_name: team01-f25-16
pull_requests: [{"author":{"id":"U_kgDOBnO7gw","is_bot":false,"login":"quinnkos","name":"Quinn Koster"},"headRefName":"quinn.feature/add-UCSBOrganization-delete-endpoint","number":72,"title":"Quinn.feature/add ucsb organization delete endpoint","url":"https://github.com/ucsb-cs156-f25/team01-f25-16/pull/72"},{"author":{"id":"MDQ6VXNlcjQyNTIxODgw","is_bot":false,"login":"omar882","name":"Omar Aboutaleb"},"headRefName":"HelpRequest-delete-single","number":71,"title":"Added UPDATE endpoint for HelpRequest and added tests","url":"https://github.com/ucsb-cs156-f25/team01-f25-16/pull/71"},{"author":{"id":"U_kgDOCBQ7GQ","is_bot":false,"login":"Saqif-Ayaan","name":""},"headRefName":"controller-recommendation-requests-run2","number":69,"title":"added controller Recommendation Requests","url":"https://github.com/ucsb-cs156-f25/team01-f25-16/pull/69"},{"author":{"id":"U_kgDOCM8WGw","is_bot":false,"login":"wpleee","name":"William Lee"},"headRefName":"wpleee-MenuItemReview-add-delete","number":65,"title":"Added DELETE endpoint for a specific record in MenuItemReview table","url":"https://github.com/ucsb-cs156-f25/team01-f25-16/pull/65"}]
