
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-16
owner: ucsb-cs156-f25
repo_name: team01-f25-16
pull_requests: [{"author":{"id":"U_kgDOCM8WGw","is_bot":false,"login":"wpleee","name":"William Lee"},"headRefName":"wpleee-MenuItemReview-add-delete","number":65,"title":"Added DELETE endpoint for a specific record in MenuItemReview table","url":"https://github.com/ucsb-cs156-f25/team01-f25-16/pull/65"},{"author":{"id":"MDQ6VXNlcjQyNTIxODgw","is_bot":false,"login":"omar882","name":"Omar Aboutaleb"},"headRefName":"omar-HelpRequest-get-single","number":62,"title":"Add GET endpoint for HelpRequest table and added tests","url":"https://github.com/ucsb-cs156-f25/team01-f25-16/pull/62"},{"author":{"id":"U_kgDOBnO7gw","is_bot":false,"login":"quinnkos","name":"Quinn Koster"},"headRefName":"quinn.feature/create-UCSBOrganizationController","number":59,"title":"add controller for UCSBOrganization","url":"https://github.com/ucsb-cs156-f25/team01-f25-16/pull/59"}]
